<?php
require_once __DIR__ . '/../config/config.php';
$page = $_GET['page'] ?? 'home';

// Serve static assets directly if requested (js, css, images, etc)
$uri = $_SERVER['REQUEST_URI'];
if (preg_match('/\.(js|css|png|jpg|jpeg|gif|ico)$/', $uri)) {
    $file = __DIR__ . parse_url($uri, PHP_URL_PATH);
    if (file_exists($file)) {
        $mime = mime_content_type($file);
        header('Content-Type: ' . $mime);
        readfile($file);
        exit;
    } else {
        http_response_code(404);
        exit('File not found');
    }
}

if (isset($_POST['download']) && isset($_GET['page']) && $_GET['page'] === 'admin_sales_report') {
    require_once __DIR__ . '/../app/models/Sale.php';
    require_once __DIR__ . '/../app/models/Therapist.php';
    require_once __DIR__ . '/../app/models/Service.php';
    $start_date = $_POST['start_date'] ?? '';
    $end_date = $_POST['end_date'] ?? '';
    $therapist_id = $_POST['therapist_id'] ?? '';
    $service_id = $_POST['service_id'] ?? '';
    $sales = Sale::getAll($start_date, $end_date, $therapist_id, $service_id);
    if ($_POST['download'] === 'excel') {
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="sales_report.csv"');
        $output = fopen('php://output', 'w');
        fputcsv($output, ['No', 'Appointment #', 'Customer Name', 'Service', 'Therapist', 'Date', 'Amount (RM)']);
        $i = 1;
        foreach ($sales as $s) {
            fputcsv($output, [
                $i++, $s['appointment_id'], $s['customer_name'], $s['service_name'], $s['therapist_name'], $s['date'], number_format($s['amount'], 2)
            ]);
        }
        fclose($output);
        exit;
    } elseif ($_POST['download'] === 'pdf') {
        session_start();
        $admin_name = isset($_SESSION['user']['admin_name']) ? $_SESSION['user']['admin_name'] : 'Admin';
        $total = 0;
        echo '<html><head><title>Sales Report</title><style>body{font-family:Arial,sans-serif;}table{border-collapse:collapse;width:100%;margin-top:16px;}th,td{border:1px solid #ccc;padding:8px;text-align:center;}th{background:#eee;} .info-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;} .info-block{font-size:1rem;text-align:left;} .total-block{font-size:1.1rem;text-align:right;font-weight:bold;}</style></head><body>';
        echo '<h1 style="text-align:center;font-size:2.2rem;font-weight:700;margin-bottom:0.5rem;">Sales Report</h1>';
        echo '<div class="info-row">';
        echo '<div class="info-block">';
        echo '<div><b>Date Range:</b> ' . htmlspecialchars($start_date) . ' to ' . htmlspecialchars($end_date) . '</div>';
        echo '<div><b>Generated by:</b> ' . htmlspecialchars($admin_name) . '</div>';
        echo '<div><b>Generated at:</b> ' . date('Y-m-d H:i') . '</div>';
        echo '</div>';
        echo '<div class="total-block">Total Sales: RM <span id="total-sales"></span></div>';
        echo '</div>';
        echo '<table><thead><tr><th>No</th><th>Appointment #</th><th>Customer Name</th><th>Service</th><th>Therapist</th><th>Date</th><th>Amount (RM)</th></tr></thead><tbody>';
        $i = 1;
        foreach ($sales as $s) {
            $total += $s['amount'];
            echo '<tr>';
            echo '<td>' . $i++ . '</td>';
            echo '<td>' . htmlspecialchars($s['appointment_id']) . '</td>';
            echo '<td>' . htmlspecialchars($s['customer_name']) . '</td>';
            echo '<td>' . htmlspecialchars($s['service_name']) . '</td>';
            echo '<td>' . htmlspecialchars($s['therapist_name']) . '</td>';
            echo '<td>' . htmlspecialchars($s['date']) . '</td>';
            echo '<td>' . number_format($s['amount'], 2) . '</td>';
            echo '</tr>';
        }
        echo '</tbody></table>';
        echo '<script>document.getElementById("total-sales").textContent = "' . number_format($total,2) . '";</script>';
        echo '<script>window.onload=function(){window.print();setTimeout(function(){window.location.href=\'/public/index.php?page=admin_sales_report&generate=1&start_date=' . htmlspecialchars($start_date) . '&end_date=' . htmlspecialchars($end_date) . '\';},1000);}</script>';
        echo '</body></html>';
        exit;
    }
}

if ($page === 'booking') {
    require_once '../app/controllers/AppointmentsController.php';
    $controller = new AppointmentsController();
    $controller->booking_form();
    exit;
}

if ($page === 'services') {
    require_once '../app/controllers/ServicesController.php';
    $controller = new ServicesController();
    $controller->index();
    exit;
}

if ($page === 'appointments') {
    require_once '../app/controllers/AppointmentsController.php';
    $controller = new AppointmentsController();
    $controller->history();
    exit;
}

if ($page === 'feedback') {
    require_once '../app/controllers/AppointmentsController.php';
    $controller = new AppointmentsController();
    $controller->feedback();
    exit;
}

if ($page === 'register') {
    require_once '../app/controllers/UserController.php';
    $controller = new UserController();
    $controller->register();
    exit;
}

if ($page === 'login') {
    require_once '../app/controllers/UserController.php';
    $controller = new UserController();
    $controller->login();
    exit;
}

if ($page === 'admin_dashboard') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->dashboard();
    exit;
}

if ($page === 'admin_services') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->services();
    exit;
}

if ($page === 'admin_add_service') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->add_service();
    exit;
}

if ($page === 'admin_edit_service') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->edit_service();
    exit;
}

if ($page === 'admin_therapists') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->therapists();
    exit;
}

if ($page === 'admin_add_therapist') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->add_therapist();
    exit;
}

if ($page === 'admin_appointments') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->appointments();
    exit;
}


if ($page === 'admin_today_appointments') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->today_appointments();
    exit;
}

if ($page === 'admin_sales_report') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->sales_report();
    exit;
}

if ($page === 'admin_profile') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->profile();
    exit;
}

if ($page === 'admin_edit_therapist') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->edit_therapist();
    exit;
}

if ($page === 'admin_add_appointment') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->add_appointment();
    exit;
}

if ($page === 'therapist_dashboard') {
    require_once '../app/controllers/TherapistController.php';
    $controller = new TherapistController();
    $controller->dashboard();
    exit;
}

if ($page === 'therapist_profile') {
    require_once '../app/controllers/TherapistController.php';
    $controller = new TherapistController();
    $controller->profile();
    exit;
}

if ($page === 'therapist_change_password') {
    require_once '../app/controllers/TherapistController.php';
    $controller = new TherapistController();
    $controller->change_password();
    exit;
}

if ($page === 'therapist_availability') {
    require_once '../app/controllers/AppointmentsController.php';
    $controller = new AppointmentsController();
    $controller->availability();
    exit;
}

if ($page === 'manage_feedback') {
    require_once '../app/controllers/AdminController.php';
    $controller = new AdminController();
    $controller->manage_feedback();
    exit;
}

if ($page === 'all_feedback') {
    require_once '../app/controllers/AppointmentsController.php';
    $controller = new AppointmentsController();
    $controller->all_feedback();
    exit;
}

// Default: booking page
require_once '../app/controllers/AppointmentsController.php';
$controller = new AppointmentsController();
$controller->booking_form(); 